#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Shuichiro Fujisawa
# SPDX-License-Identifier: BSD-3-Clause

import sys

for nums in sys.stdin:
    bigline = []
    if int(nums) == 1:#例外処理
        bigline.append([1, 1])

    x = int(nums)
    n = 1
    for i in range(1,x + 1):
        ### 素数掃き出し ###
        n = 1
        fl = 0
        while n <= i:
            if i % n == 0:
                fl += 1
            n += 1
        #-------------------
        if fl == 2:
            line = []
            e = 0
            while x % i == 0:
                x = x / i
                e += 1
            if e > 0:
                exp = "^" + str(e)
                line.append(i)
                line.append(exp)
                bigline.append(line)

    print( str(nums) + "=" + str(bigline))


